### ISSUE TITLE
Error on using with nuxt

### ISSUE THREAD

**Issue by ram-you** [sainf/vue2-siema#1]
Error on using with nuxt

```
(function (exports, require, module, __filename, __dirname) { import Siema from './siema.vue'
 SyntaxError: Unexpected token import
```

**Comment by sainf** [comment]
Hi,

I'm also using the nuxt, and it works very well.

I just made a git with a https://github.com/nuxt-community/starter-template and vue 2 siema.
https://github.com/sainf/nuxt-siema-demo

After installing nuxt and adding vue2-siema its just a small config, check my second commit.
https://github.com/sainf/nuxt-siema-demo/commit/03be62d0f94412cb31ca68c3ddba1084c3150bb5

If you still have problems, please give me more info.

**Comment by PhouvanhKCSV** [comment]
Will this library fully support Nuxtjs SSR?

**Comment by sainf** [comment]
Not for now...

Siema mentors are making the 2.0 version so, I'm delaying any big changes to this library.
